# Generated by Django 5.2.13 on 2026-04-08 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_item',
            name='image',
            field=models.ImageField(blank=True, upload_to='products/'),
        ),
    ]
