# Generated by Django 5.2.13 on 2026-04-17 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_ecommerce', '0003_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='image',
            field=models.ImageField(blank=True, upload_to='products/'),
        ),
    ]
