# Generated by Django 5.2.13 on 2026-05-23 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_ecommerce', '0004_cart_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_product',
            name='user',
        ),
        migrations.DeleteModel(
            name='order_items',
        ),
        migrations.DeleteModel(
            name='order_product',
        ),
    ]
